### ISSUE TITLE
Additional charts needed

### ISSUE THREAD

**Issue by vt102** [pjlewis505/wrath-of-the-autarch#12]
I feel this game's accessibility would be greatly increased by the following charts:
- A chart showing the effects of Stability, and all the ways stability can be raised and lowered.
- A chart showing the effects of Disposition, and all the way disposition can be raised and lowered.
- A chart showing the Fate results (loss, tie, success, success with style) and what happens with each Fate action on that result (Overcome/loss, Overcome/tie, etc...)

Currently, this info seems scattered throughout the book.  It would be a great relief to have it all in one place.

**Comment by vt102** [comment]
I think also how to get skill advancements-- there's at least 3 different ways, not sure if I'm missing some.  1) Complete mission, 2) roll vs. higher opposition, and 3) Sit mission out?

**Comment by pjlewis505** [comment]
Will work to add that to the summaries! May need to work with the graphic designer to add some of that. Also, are you using the most recent sheets that are on github? They're better about adding in hints for what those do to the various tracks.
