### ISSUE TITLE
Skill advances for opposed rolls?

### ISSUE THREAD

**Issue by vt102** [pjlewis505/wrath-of-the-autarch#14]
> Any time during the challenge phase that a hero
> attempts an action with an opposition higher than the
> skill used for the action, they get one advance for the
> skill.

It's not clear that this applies to opposed rolls.  I assume if the opposition skill is higher than your skill, you would get an advancement, even though the actual result may not be.

**Comment by pjlewis505** [comment]
Ah, so, skill advances are only for the challenge phase, not the conflict. I added some language to make that more explicit.
