### ISSUE TITLE
Campaign Aspect creation inconsistency

### ISSUE THREAD

**Issue by vt102** [pjlewis505/wrath-of-the-autarch#2]
Page 16:

"Terri is playing the character Gwynnet. Traveling through the Dusk’s Ayrie, she has the idea of creating a new campaign aspect related to the flora of the area."

Explicitly, Terri is playing a character in the challenge scene, and creating a campaign aspect.  However, page 45 states, "As with mission aspects, campaign aspects may not be created by a Stronghold player whose hero is in a challenge scene."

**Comment by pjlewis505** [comment]
Hmm. I need to make this more explicit somehow that this isn't a challenge scene, rather it's just at some point during the mission. Have to check what concepts I've introduced by this point.

**Comment by pjlewis505** [comment]
Clarified this occurred as part of an advantage scene
