### ISSUE TITLE
No aspect burning in Diplomacy conflict scenes?

### ISSUE THREAD

**Issue by vt102** [pjlewis505/wrath-of-the-autarch#3]
Since the other three had options to burn aspects, this struck me as a possible oversight.

**Comment by pjlewis505** [comment]
Hi Andy!

Thanks for the input! I didn't realize anyone was looking at github. I'll make it a point to get the latest marked up text versions up. Definitely works better as a repository for those than for things like Word or Indesign files. :)

**Comment by pjlewis505** [comment]
I added an outlet for aspect burning during diplomacy.
