### ISSUE TITLE
Not enough room for aspects on char sheet

### ISSUE THREAD

**Issue by vt102** [pjlewis505/wrath-of-the-autarch#6]
According to the Characters chapter, characters should have five aspects-- Concept, Trouble, Legacy, and two "flexible" ones.  The character sheet does not have places for the two general aspects to be written.

**Comment by vt102** [comment]
Are the "flexible" aspects meant to be the relationship aspects?

**Comment by pjlewis505** [comment]
Yeah, those flexible ones did get turned into relationship aspects. I went ahead and updated the characters chapter to only refer to three aspects for heroes.
