### ISSUE TITLE
Faction Growth in summary, but not in text

### ISSUE THREAD

**Issue by vt102** [pjlewis505/wrath-of-the-autarch#7]
Faction Growth is listed in the Season summary page, but it does not seem to appear in the text under that term.

**Comment by vt102** [comment]
I assume it's this, under Seasons: Spring:

> Additionally, there may be stability increases for
> the other factions. The cards are shuffled, and one card
> is drawn for each faction (including the Empire). If the
> result is +2 or higher, the faction gains a stability. See
> the Factions chapter for more details on how stability
> works.

Going through the Season summary page, I searched the term for more info, and was unable to find it.  Perhaps a subheading for the above entitled, "Faction Growth?"

**Comment by pjlewis505** [comment]
Good catch! I added a heading called Faction Growth to the seasons chapter.
